# -*- coding: utf-8 -*-
"""pi05lerobot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qkzgwYEFR8Asiw0iweO-TtYWk25dRi1v

# Pi0.5 / LeRobot Fine-Tuning on Colab

This notebook is prepared for:

```text
Dataset: sebry4n/lerobot_rian_dataset_3_20260701_135607
Policy:  pi05
Base:    lerobot/pi05_base
```

The notebook is designed for Google Colab. It includes:

1. GPU and VRAM check
2. Google Drive mounting
3. LeRobot + Pi0.5 dependency install
4. Hugging Face login
5. Dataset sanity check
6. Tiny debug training
7. Full fine-tuning mode
8. Expert-only fallback mode
9. Checkpoint discovery and optional upload
10. Single-frame inference sanity check

## Important hardware warning

Full Pi0.5 fine-tuning is extremely VRAM-heavy. The OpenPI repo lists full fine-tuning as needing **more than 70 GB GPU memory**. In practice, that means A100 80GB / H100-class hardware.

If Colab gives you T4, L4, V100, or A100 40GB, use `TRAIN_MODE = "expert_only"` or a smaller policy instead of full fine-tuning.

## 1. Configuration

Change only this first cell most of the time.

Recommended flow:

```text
First run:
TRAIN_MODE = "debug_full"

If debug succeeds and GPU is A100 80GB:
TRAIN_MODE = "full"

If GPU is L4 / A100 40GB / RTX 4090-like:
TRAIN_MODE = "expert_only"
```

`debug_full` only runs 10 steps. It is meant to catch installation, dataset, and model-loading errors before you waste time.
"""

# ===== User configuration =====

DATASET_REPO_ID = "Kamna0321/so101_persepsi_robot"

# Change this if you want to push a trained model to your own Hugging Face account.
# Example: "your_username/pi05_rian_full"
HF_MODEL_REPO_ID = "poi69420/pi05_v2"

# LeRobot's trainer has policy.push_to_hub=True BY DEFAULT, which:
#   1) fails training at startup if no repo_id is set, and
#   2) auto-uploads every run (even 10-step debug runs) to the Hub.
# Keep this False and use the manual upload cell at the end instead.
PUSH_TO_HUB_DURING_TRAINING = False

# Choose one:
# "debug_full"  = 10-step test using full-training flags
# "full"        = full fine-tuning intention, requires ~80GB VRAM
# "expert_only" = lower-memory fallback, not full fine-tuning
TRAIN_MODE = "full"

# Training length. These are used only for the matching mode.
DEBUG_STEPS = 10
FULL_STEPS = 3000
EXPERT_ONLY_STEPS = 3000

# Batch sizes. Reduce if CUDA OOM happens.
DEBUG_BATCH_SIZE = 1
FULL_BATCH_SIZE = 4
EXPERT_ONLY_BATCH_SIZE = 1

# Keep false unless you intentionally want Weights & Biases logging.
USE_WANDB = False

# Save outputs to Drive so Colab disconnects do not erase everything.
USE_GOOGLE_DRIVE = True
DRIVE_OUTPUT_ROOT = "/content/drive/MyDrive/lerobot_runs"

# Some datasets lack quantile stats. This fallback is recommended by the Pi0.5 docs.
USE_MEAN_STD_NORMALIZATION_FALLBACK = True

# Safety: prevent accidental full fine-tuning on weak GPUs.
# Set True only if you understand the memory risk.
OVERRIDE_VRAM_SAFETY = True

# Optional. Leave empty for normal latest install.
# You may pin a commit if your group wants reproducibility:
# LEROBOT_GIT_REF = "@<commit_hash>"
LEROBOT_GIT_REF = ""

"""## 2. Check GPU"""

import subprocess
import os
from pathlib import Path

def run(cmd, check=True, capture=False):
    print(f"\n$ {cmd}")
    if capture:
        return subprocess.run(cmd, shell=True, check=check, text=True,
                              stdout=subprocess.PIPE, stderr=subprocess.STDOUT).stdout
    return subprocess.run(cmd, shell=True, check=check)

# Show GPU info.
try:
    gpu_info = run(
        "nvidia-smi --query-gpu=name,memory.total --format=csv,noheader,nounits",
        capture=True,
    )
    print(gpu_info)
    first_line = gpu_info.strip().splitlines()[0]
    gpu_name, gpu_mem_mb = first_line.split(",")
    gpu_name = gpu_name.strip()
    gpu_mem_mb = int(gpu_mem_mb.strip())
    gpu_mem_gb = gpu_mem_mb / 1024
except Exception as e:
    gpu_name = None
    gpu_mem_mb = 0
    gpu_mem_gb = 0
    print("Could not read GPU info:", repr(e))

print(f"GPU name: {gpu_name}")
print(f"VRAM: {gpu_mem_gb:.2f} GB")

if gpu_mem_mb >= 70000:
    print("Good: this looks suitable for attempting full Pi0.5 fine-tuning.")
elif gpu_mem_mb >= 23000:
    print("Warning: likely not enough for full Pi0.5 fine-tuning. Use expert_only unless you know what you are doing.")
elif gpu_mem_mb > 0:
    print("Warning: too small for Pi0.5 fine-tuning. You can still test installs/dataset loading.")
else:
    print("No GPU detected. In Colab, go to Runtime > Change runtime type > GPU.")

"""## 3. Mount Google Drive"""

from pathlib import Path

if USE_GOOGLE_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    Path(DRIVE_OUTPUT_ROOT).mkdir(parents=True, exist_ok=True)
    OUTPUT_ROOT = DRIVE_OUTPUT_ROOT
else:
    OUTPUT_ROOT = "/content/lerobot_runs"
    Path(OUTPUT_ROOT).mkdir(parents=True, exist_ok=True)

print("OUTPUT_ROOT:", OUTPUT_ROOT)

"""## 4. Install system packages and LeRobot"""

# System packages.
run("apt-get update -qq")
run("apt-get install -y -qq git git-lfs ffmpeg")
run("git lfs install")

# Python packages.
run("python -m pip install -U pip setuptools wheel")

# Install LeRobot with Pi + training/dataset dependencies.
# NOTE: the [pi] extra alone only installs the policy deps. Loading a
# LeRobotDataset and running lerobot-train also need the [training] extra
# (which pulls in [dataset]: av/PyAV, torchcodec, datasets, jsonlines, accelerate).
lerobot_install = f"'lerobot[pi,training]@git+https://github.com/huggingface/lerobot.git{LEROBOT_GIT_REF}'"
run(f"python -m pip install -U {lerobot_install}")

print("Install finished.")

"""## 5. Optional: inspect installed CLI flags

This helps if LeRobot changes argument names later.  
If `--policy.pretrained_path` errors, check this cell output.
"""

help_text = run("lerobot-train --help", capture=True, check=False)

keys = [
    "pretrained", "policy.path", "train_expert", "freeze_vision",
    "dtype", "batch_size", "normalization", "compile_model", "push_to_hub",
]
matching = [line for line in help_text.splitlines() if any(k in line for k in keys)]
print("\n".join(matching[:120]))

"""## 6. Hugging Face login"""

from huggingface_hub import notebook_login, whoami

print("Log in with a Hugging Face token.")
print("Use a token with write permission if you want to push the trained checkpoint.")
notebook_login()

try:
    print("Logged in as:", whoami()["name"])
except Exception as e:
    print("Login check failed:", repr(e))

"""## 7. Load and inspect the dataset"""

from lerobot.datasets.lerobot_dataset import LeRobotDataset
import torch
import numpy as np

print("Loading dataset:", DATASET_REPO_ID)
ds = LeRobotDataset(DATASET_REPO_ID)

print("Dataset length:", len(ds))

print("\nFeatures:")
for k, v in ds.features.items():
    print(f"- {k}: {v}")

sample = ds[0]

print("\nSample keys:")
for k in sample.keys():
    print("-", k)

# Detect camera keys dynamically instead of hard-coding "top"/"wrist".
image_keys = sorted(k for k in sample.keys() if k.startswith("observation.images."))
print("\nDetected image keys:", image_keys)

print("\nImportant shapes:")
for key in ["action", "observation.state", *image_keys]:
    if key in sample:
        value = sample[key]
        shape = getattr(value, "shape", None)
        print(f"{key}: type={type(value)}, shape={shape}")
    else:
        print(f"{key}: MISSING")

# Basic sanity checks.
assert "action" in sample, "Dataset has no action field."
assert "observation.state" in sample, "Dataset has no observation.state field."
assert len(image_keys) > 0, "Dataset has no observation.images.* fields."

print("\nDataset sanity check passed.")

"""## 8. Display one sample image"""

import matplotlib.pyplot as plt

def to_numpy_image(x):
    # Convert common LeRobot image tensor/PIL/numpy formats to HWC numpy image.
    if hasattr(x, "detach"):
        x = x.detach().cpu()
    if hasattr(x, "numpy"):
        x = x.numpy()
    arr = np.array(x)

    # CHW -> HWC
    if arr.ndim == 3 and arr.shape[0] in [1, 3, 4] and arr.shape[-1] not in [1, 3, 4]:
        arr = np.transpose(arr, (1, 2, 0))

    # Normalize for display if needed.
    if arr.dtype != np.uint8:
        arr_min, arr_max = float(np.nanmin(arr)), float(np.nanmax(arr))
        if arr_max <= 1.0:
            arr = (arr * 255).clip(0, 255).astype(np.uint8)
        else:
            arr = arr.clip(0, 255).astype(np.uint8)
    return arr

print("Image keys:", image_keys)

for key in image_keys:
    img = to_numpy_image(sample[key])
    plt.figure(figsize=(6, 4))
    plt.imshow(img)
    plt.title(key)
    plt.axis("off")
    plt.show()

"""## 9. Build the training command

Mode behavior:

```text
debug_full:
  freeze_vision_encoder=false
  train_expert_only=false
  steps=10
  batch_size=1
  compile_model=false

full:
  freeze_vision_encoder=false
  train_expert_only=false
  steps=3000 by default
  batch_size=4 by default
  compile_model=true

expert_only:
  freeze_vision_encoder=true
  train_expert_only=true
  steps=3000 by default
  batch_size=1 by default
  compile_model=false
```

`expert_only` is not full fine-tuning. It freezes the VLM and trains the action expert/projections, which is much more likely to fit on Colab GPUs.
"""

import shlex
from datetime import datetime

def bool_str(x):
    return "true" if bool(x) else "false"

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

if TRAIN_MODE == "debug_full":
    job_name = f"pi05_rian_debug_full_{timestamp}"
    steps = DEBUG_STEPS
    batch_size = DEBUG_BATCH_SIZE
    compile_model = False
    freeze_vision_encoder = False
    train_expert_only = False

elif TRAIN_MODE == "full":
    job_name = f"pi05_rian_full_{timestamp}"
    steps = FULL_STEPS
    batch_size = FULL_BATCH_SIZE
    compile_model = True
    freeze_vision_encoder = False
    train_expert_only = False

    if gpu_mem_mb < 70000 and not OVERRIDE_VRAM_SAFETY:
        raise RuntimeError(
            f"TRAIN_MODE='full' requested, but detected VRAM is only {gpu_mem_gb:.2f} GB. "
            "Full Pi0.5 fine-tuning typically needs >70GB VRAM. "
            "Use TRAIN_MODE='expert_only', use A100 80GB/H100, or set OVERRIDE_VRAM_SAFETY=True."
        )

elif TRAIN_MODE == "expert_only":
    job_name = f"pi05_rian_expert_only_{timestamp}"
    steps = EXPERT_ONLY_STEPS
    batch_size = EXPERT_ONLY_BATCH_SIZE
    compile_model = False
    freeze_vision_encoder = True
    train_expert_only = True

    if gpu_mem_mb < 22000:
        print(
            f"Warning: detected VRAM is only {gpu_mem_gb:.2f} GB. "
            "Even expert_only Pi0.5 training may OOM."
        )

else:
    raise ValueError(f"Unknown TRAIN_MODE: {TRAIN_MODE}")

output_dir = f"{OUTPUT_ROOT}/{job_name}"

# LeRobot defaults policy.push_to_hub to TRUE. If we don't set it explicitly,
# training either crashes at startup ("'repo_id' argument missing") when no
# repo_id is given, or silently uploads every debug run to the Hub.
push_to_hub = bool(PUSH_TO_HUB_DURING_TRAINING)
if push_to_hub and not HF_MODEL_REPO_ID:
    raise ValueError("PUSH_TO_HUB_DURING_TRAINING=True requires HF_MODEL_REPO_ID to be set.")

cmd = [
    "lerobot-train",
    f"--dataset.repo_id={DATASET_REPO_ID}",
    "--policy.type=pi05",
    "--policy.pretrained_path=lerobot/pi05_base",
    f"--output_dir={output_dir}",
    f"--job_name={job_name}",
    "--policy.device=cuda",
    "--policy.dtype=bfloat16",
    f"--policy.compile_model={bool_str(compile_model)}",
    "--policy.gradient_checkpointing=true",
    f"--policy.freeze_vision_encoder={bool_str(freeze_vision_encoder)}",
    f"--policy.train_expert_only={bool_str(train_expert_only)}",
    f"--policy.push_to_hub={bool_str(push_to_hub)}",
    f"--batch_size={batch_size}",
    f"--steps={steps}",
    f"--wandb.enable={bool_str(USE_WANDB)}",
]

# repo_id is only needed when pushing from the trainer itself.
if push_to_hub:
    cmd.append(f"--policy.repo_id={HF_MODEL_REPO_ID}")

# Normalization fallback recommended by the Pi0.5 docs when quantile stats are missing.
if USE_MEAN_STD_NORMALIZATION_FALLBACK:
    cmd.append('--policy.normalization_mapping={"ACTION": "MEAN_STD", "STATE": "MEAN_STD", "VISUAL": "IDENTITY"}')

print("TRAIN_MODE:", TRAIN_MODE)
print("JOB_NAME:", job_name)
print("OUTPUT_DIR:", output_dir)
print("\nCommand:")
print(" \\\n  ".join(shlex.quote(x) for x in cmd))

"""## 10. Run training (with live progress charts)

This cell streams the trainer's logs and live-plots **loss**, **grad norm**, and **learning rate** against the training step. The last ~15 raw log lines are shown under the charts, so errors are still visible.

Notes:

- LeRobot only prints a metrics line every `log_freq` steps (default is fine for this notebook; the 10-step debug run logs a handful of points).
- If you prefer full raw console output with no charts, use the plain-run cell in the next section.
- If you want hosted dashboards instead, set `USE_WANDB = True` in the config cell and log in to Weights & Biases when prompted.

"""

# This cell actually starts training WITH live progress visualization.
# For the first run, keep TRAIN_MODE='debug_full' so it only runs 10 steps.
#
# It streams lerobot-train's console output, parses the metric lines
# (step / loss / grdn / lr), and redraws a matplotlib chart every few
# log lines. Full raw logs are still printed below the chart.

import re
import subprocess
import collections
import matplotlib.pyplot as plt
from IPython.display import display, clear_output

# lerobot logs steps via format_big_number: "250", "1K", "1.5K", "2M", ...
_SUFFIX = {"": 1, "K": 1e3, "M": 1e6, "B": 1e9, "T": 1e12, "Q": 1e15}

def parse_big_number(s):
    m = re.fullmatch(r"([\d.]+)([KMBTQ]?)", s.strip())
    if not m:
        return None
    return float(m.group(1)) * _SUFFIX[m.group(2)]

METRIC_RE = re.compile(
    r"step:(?P<step>[\d.]+[KMBTQ]?).*?"
    r"loss:(?P<loss>[\d.eE+-]+)"
    r"(?:.*?grdn:(?P<grdn>[\d.eE+-]+))?"
    r"(?:.*?lr:(?P<lr>[\d.eE+-]+))?"
)

history = {"step": [], "loss": [], "grdn": [], "lr": []}
log_tail = collections.deque(maxlen=15)  # last lines shown under the chart

def redraw():
    clear_output(wait=True)
    fig, axes = plt.subplots(1, 3, figsize=(15, 3.5))

    axes[0].plot(history["step"], history["loss"], marker=".", lw=1)
    axes[0].set_title("loss"); axes[0].set_xlabel("step"); axes[0].grid(alpha=0.3)
    if history["loss"] and min(history["loss"]) > 0:
        axes[0].set_yscale("log")

    g = [(s, v) for s, v in zip(history["step"], history["grdn"]) if v is not None]
    if g:
        axes[1].plot([x for x, _ in g], [y for _, y in g], marker=".", lw=1, color="tab:orange")
    axes[1].set_title("grad norm"); axes[1].set_xlabel("step"); axes[1].grid(alpha=0.3)

    l = [(s, v) for s, v in zip(history["step"], history["lr"]) if v is not None]
    if l:
        axes[2].plot([x for x, _ in l], [y for _, y in l], marker=".", lw=1, color="tab:green")
    axes[2].set_title("learning rate"); axes[2].set_xlabel("step"); axes[2].grid(alpha=0.3)

    if history["step"]:
        fig.suptitle(
            f"{job_name}   |   step {history['step'][-1]:.0f} / {steps}   |   "
            f"last loss {history['loss'][-1]:.4f}",
            y=1.05,
        )
    plt.tight_layout(); plt.show()

    print("---- recent log lines ----")
    for line in log_tail:
        print(line)

print("Starting training...")
print("Output dir:", output_dir)

proc = subprocess.Popen(
    cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    text=True, bufsize=1,
)

lines_since_draw = 0
try:
    for raw_line in proc.stdout:
        line = raw_line.rstrip()
        if not line:
            continue
        log_tail.append(line)

        m = METRIC_RE.search(line)
        if m:
            step_val = parse_big_number(m.group("step"))
            if step_val is not None:
                history["step"].append(step_val)
                history["loss"].append(float(m.group("loss")))
                history["grdn"].append(float(m.group("grdn")) if m.group("grdn") else None)
                history["lr"].append(float(m.group("lr")) if m.group("lr") else None)
                redraw()
                lines_since_draw = 0
                continue

        # Refresh the log tail periodically even when no metric line appears
        # (e.g. during the long model download / compile phase).
        lines_since_draw += 1
        if lines_since_draw >= 40:
            redraw()
            lines_since_draw = 0
finally:
    proc.stdout.close()
    returncode = proc.wait()

redraw()
if returncode != 0:
    raise RuntimeError(f"Training command failed with return code {returncode}")

print("\nTraining finished.")

"""### 10b. Alternative: plain run (no live charts)

Use this instead of the cell above if the live plotting ever gets in the way (it is functionally identical to the original run cell). You can re-plot afterwards with the cell below it, which reads the metrics back from the saved log history.

"""

# Plain training run without live charts. Run EITHER this cell OR the one above, not both.

RUN_PLAIN = False  # set True to use this cell

if RUN_PLAIN:
    import subprocess
    print("Starting training...")
    print("Output dir:", output_dir)
    process = subprocess.run(cmd, text=True)
    if process.returncode != 0:
        raise RuntimeError(f"Training command failed with return code {process.returncode}")
    print("Training finished.")
else:
    print("RUN_PLAIN is False. Use the live-chart cell above, or set RUN_PLAIN=True here.")

# Post-hoc plot: redraws the final training curves from the parsed history
# collected by the live-chart cell. Handy after the run finishes, or to
# save the figure to Drive.

import matplotlib.pyplot as plt

if "history" in dir() and history["step"]:
    fig, axes = plt.subplots(1, 3, figsize=(15, 3.5))
    axes[0].plot(history["step"], history["loss"], marker=".", lw=1)
    axes[0].set_title("loss"); axes[0].set_xlabel("step"); axes[0].grid(alpha=0.3)

    g = [(s, v) for s, v in zip(history["step"], history["grdn"]) if v is not None]
    if g:
        axes[1].plot([x for x, _ in g], [y for _, y in g], marker=".", lw=1, color="tab:orange")
    axes[1].set_title("grad norm"); axes[1].set_xlabel("step"); axes[1].grid(alpha=0.3)

    l = [(s, v) for s, v in zip(history["step"], history["lr"]) if v is not None]
    if l:
        axes[2].plot([x for x, _ in l], [y for _, y in l], marker=".", lw=1, color="tab:green")
    axes[2].set_title("learning rate"); axes[2].set_xlabel("step"); axes[2].grid(alpha=0.3)

    fig.suptitle(job_name)
    plt.tight_layout()

    # Also save the figure next to the checkpoints (on Drive if enabled).
    fig_path = f"{output_dir}/training_curves.png"
    try:
        fig.savefig(fig_path, dpi=150, bbox_inches="tight")
        print("Saved figure to:", fig_path)
    except Exception as e:
        print("Could not save figure:", repr(e))
    plt.show()
else:
    print("No training history found. Run the live-chart training cell first.")

"""## 11. If `--policy.pretrained_path` fails

Only run this cell if the previous training cell errors specifically because `policy.pretrained_path` is not recognized.

Some versions of the tooling may use `--policy.path` instead.
"""

# Fallback command variant: replace --policy.pretrained_path with --policy.path.
# Run this only if the normal command failed because pretrained_path is not recognized.
#
# Note: when using --policy.path, the policy config (including its type) is loaded
# from the checkpoint itself, so --policy.type must be REMOVED. Passing both can
# conflict.

'''cmd_policy_path = []
for arg in cmd:
    if arg.startswith("--policy.pretrained_path="):
        cmd_policy_path.append(arg.replace("--policy.pretrained_path=", "--policy.path="))
    elif arg.startswith("--policy.type="):
        continue  # type comes from the loaded checkpoint config
    else:
        cmd_policy_path.append(arg)

print("Fallback command:")
print(" \\\n  ".join(shlex.quote(x) for x in cmd_policy_path))'''

# Uncomment to run:
# process = subprocess.run(cmd_policy_path, text=True)
# if process.returncode != 0:
#     raise RuntimeError(f"Fallback training command failed with return code {process.returncode}")

"""## 12. Find saved checkpoints"""

from pathlib import Path
import os

out = Path(output_dir)
print("Listing output directory:", out)

if out.exists():
    printed = 0
    for p in sorted(out.rglob("*")):
        # Avoid printing too many files.
        if len(str(p.relative_to(out)).split(os.sep)) <= 4:
            print(p)
            printed += 1
            if printed > 200:
                print("... truncated listing ...")
                break

def looks_like_model_dir(p: Path) -> bool:
    return p.is_dir() and any((p / f).exists() for f in ["config.json", "model.safetensors", "train_config.json"])

# Preference order:
# 1. checkpoints/last/pretrained_model  (what from_pretrained expects)
# 2. newest checkpoints/<step>/pretrained_model
# 3. any pretrained_model dir
CHECKPOINT_DIR = None

last_pm = out / "checkpoints" / "last" / "pretrained_model"
if looks_like_model_dir(last_pm):
    CHECKPOINT_DIR = last_pm
else:
    pm_dirs = sorted(p for p in out.glob("checkpoints/*/pretrained_model") if looks_like_model_dir(p))
    if pm_dirs:
        CHECKPOINT_DIR = pm_dirs[-1]
    else:
        pm_dirs = sorted(p for p in out.rglob("pretrained_model") if looks_like_model_dir(p))
        if pm_dirs:
            CHECKPOINT_DIR = pm_dirs[-1]

if CHECKPOINT_DIR is None:
    print("\nNo trained checkpoint found under", out)
    print("The inference cell will fall back to the base model.")
    CHECKPOINT_DIR = ""
else:
    CHECKPOINT_DIR = str(CHECKPOINT_DIR)
    print("\nSelected CHECKPOINT_DIR:", CHECKPOINT_DIR)

"""## 13. Optional: upload the trained checkpoint to Hugging Face"""

# This uploads the selected checkpoint folder to HF_MODEL_REPO_ID.
# Only run if you logged in with a token that has write permission.

PUSH_TO_HUB = False  # change to True when ready

if PUSH_TO_HUB:
    from huggingface_hub import HfApi
    api = HfApi()

    assert HF_MODEL_REPO_ID, "Set HF_MODEL_REPO_ID first."
    assert CHECKPOINT_DIR, "No trained checkpoint was found. Run training and the checkpoint discovery cell first."

    print("Creating/updating model repo:", HF_MODEL_REPO_ID)
    api.create_repo(repo_id=HF_MODEL_REPO_ID, repo_type="model", exist_ok=True)

    print("Uploading folder:", CHECKPOINT_DIR)
    api.upload_folder(
        repo_id=HF_MODEL_REPO_ID,
        repo_type="model",
        folder_path=CHECKPOINT_DIR,
        commit_message=f"Upload {TRAIN_MODE} checkpoint from Colab",
    )
    print("Upload finished.")
else:
    print("PUSH_TO_HUB is False. Set it to True when you are ready.")

"""## 14. Single-frame inference sanity check

This does **not** control the robot.  
It only checks whether a trained checkpoint can load and produce an action from one dataset frame.
"""

# This can use a lot of VRAM. Restart runtime first if memory is fragmented
# (then re-run the config, dataset, and checkpoint-discovery cells).

RUN_INFERENCE_SANITY_CHECK = True  # change to True when ready

if RUN_INFERENCE_SANITY_CHECK:
    import torch
    from pathlib import Path
    from lerobot.datasets.lerobot_dataset import LeRobotDataset
    from lerobot.policies.factory import make_pre_post_processors
    from lerobot.policies.pi05 import PI05Policy

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Use the trained checkpoint only if it actually contains model files;
    # otherwise fall back to the base model.
    def has_model_files(d):
        p = Path(d)
        return d and p.is_dir() and any((p / f).exists() for f in ["config.json", "model.safetensors"])

    model_id = CHECKPOINT_DIR if has_model_files(CHECKPOINT_DIR) else "lerobot/pi05_base"
    print("Loading policy from:", model_id)

    policy = PI05Policy.from_pretrained(model_id).to(device).eval()

    preprocess, postprocess = make_pre_post_processors(
        policy.config,
        model_id,
        preprocessor_overrides={"device_processor": {"device": str(device)}},
    )

    ds_eval = LeRobotDataset(DATASET_REPO_ID)
    frame = dict(ds_eval[0])

    # Pi0.5 is language-conditioned; make sure a task string is present.
    if "task" not in frame or frame["task"] is None:
        frame["task"] = "do the task"

    batch = preprocess(frame)

    with torch.inference_mode():
        pred_action = policy.select_action(batch)
        pred_action = postprocess(pred_action)

    print("Predicted action:")
    print(pred_action)
else:
    print("RUN_INFERENCE_SANITY_CHECK is False. Set it to True when ready.")

"""## 15. What to do after training

For an actual robot demo, the trained policy output must match your robot's command format.

This dataset has:

```text
robot_type: so_follower
action shape: 6
state shape: 6
joints:
- shoulder_pan.pos
- shoulder_lift.pos
- elbow_flex.pos
- wrist_flex.pos
- wrist_roll.pos
- gripper.pos
```

So during real inference, treat the predicted action as a 6D joint/gripper command unless your robot runtime says otherwise.

Do not execute raw policy outputs at full speed. Add:

```text
- joint limits
- velocity limits
- table collision checks
- emergency stop
- low-speed first test
```

If full Pi0.5 fine-tuning fails on Colab because of CUDA OOM, that is expected unless you get A100 80GB/H100-class hardware. Use `TRAIN_MODE="expert_only"` or train a smaller policy.
"""